# Generated by Django 3.0.3 on 2020-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('bedroom_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('available_places', models.IntegerField()),
                ('busy_dates', models.DateField(verbose_name='Busy dates')),
                ('purchased', models.BooleanField()),
            ],
        ),
    ]
