# Generated by Django 3.0.3 on 2020-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('gender', models.CharField(choices=[('Feminino', 'F'), ('Masculino', 'M'), ('Outro', 'O')], max_length=10)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de telefone')),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
            ],
        ),
    ]
