# Generated by Django 3.0.3 on 2020-02-17 15:42
import datetime
from django.db import migrations

def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(
        name = "Mauricio",
        email = "mauricio.tonaki@gmail.com",
        cpf = "112.133.134.43",
        gender = 'M',
        phone_number = "(11)983274213",
        birthday = datetime.date(1991, 7, 21)
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
